DROP TABLE "EVENT";

CREATE TABLE "EVENT"
(
   EVENT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 200, INCREMENT BY 1),
   CITY varchar(30),
   EVENT_DATE date,
   PLACES_LEFT smallint DEFAULT 10,
   ENABLED boolean DEFAULT TRUE
);


INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Munich','2015-11-21');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Leeds','2015-12-01');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Swindon','2015-12-12');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Cardiff','2015-12-20');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Southampton','2016-01-11');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Copenhagen','2016-01-20');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Berlin','2016-02-01');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('London','2016-03-15');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Reading','2016-03-24');
INSERT INTO EVENT (CITY,EVENT_DATE) VALUES ('Prague','2016-04-15');



DROP TABLE "BOOKING";

CREATE TABLE "BOOKING"
(
   BOOKING_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 500, INCREMENT BY 1),
   EVENT_ID INTEGER NOT NULL, --PERHAPS A FOREIGN KEY //TODO?
   FIRST_NAME varchar(100),
   LAST_NAME varchar(100), -- FORM VALIDATION LENGTH //TODO
   EMAIL_ADDRESS varchar(100),
   COMPANY varchar(100),
   MESSAGE varchar(500),
   BOOKING_DATE date,
   ENABLED boolean DEFAULT TRUE
);


DROP TABLE "BOOKING_EMAIL";

CREATE TABLE "BOOKING_EMAIL"
(
   BOOKING_EMAIL_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 5000, INCREMENT BY 1),
   BOOKING_ID INTEGER, -- --PERHAPS A FOREIGN KEY //TODO?
   EMAIL_SENT timestamp,
   SENT_FROM varchar(100),
   SUBJECT varchar(200),
   MESSAGE varchar(2000)
);





